### ISSUE TITLE
Tests fail under Python 3.5.2

### ISSUE THREAD

**Issue by ylep** [HumanBrainProject/cortical-voluba#2]
Tests fail because of https://github.com/marshmallow-code/marshmallow/issues/1409
We are stuck with Python 3.5.2 because that is the version provided by Ubuntu 16.04 (which is used for the highres-cortex Docker image).
Reminder: close the issue and remove the workaround introduced in https://github.com/HumanBrainProject/cortical-voluba/commit/5b0fc8ca588fffb352735aa3b352c80625a236da#diff-d320868d9a0668736839b1e38cf3393d once a fix for https://github.com/marshmallow-code/marshmallow/issues/1409 is released.

**Comment by sloria** [comment]
This is fixed in marshmallow 3.2.0. Apologies for the breakage.

As a heads up: I can't promise we'll keep supporting Python 3.5.2 moving forward. Many bug fixes, security fixes, and typing improvements have been released since 3.5.2, so supporting it will be quite a maintenance burden.

**Comment by ylep** [comment]
Many thanks @sloria for acting so fast. I do realize that maintaining compatibility with old, buggy point-versions is a burden. I would love to upgrade, but on the other hand I also depend on a large C++ code base, which is only well tested under Ubuntu 16.04 or older. I will consider upgrading Python if it becomes a necessity.

Workaround removed in https://github.com/HumanBrainProject/cortical-voluba/commit/0e973b5bcb8d635c10042e3a9191df25dadb05df
